# Generated by Django 2.0.13 on 2019-03-26 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('jersey_num', models.IntegerField(blank=True)),
                ('position', models.CharField(blank=True, max_length=2, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.IntegerField(blank=True)),
                ('birth_date', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=15, null=True)),
                ('team_abbr', models.CharField(blank=True, max_length=3, null=True)),
                ('team_city', models.CharField(blank=True, max_length=20, null=True)),
                ('team_name', models.CharField(blank=True, max_length=15, null=True)),
                ('player_photo', models.ImageField(blank=True, null=True, upload_to='NBAstats')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('conference_name', models.IntegerField(blank=True)),
                ('team_abbr', models.CharField(blank=True, max_length=3, null=True)),
                ('team_city', models.CharField(blank=True, max_length=20, null=True)),
                ('team_name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NBAstats.team'),
        ),
    ]
