# Generated by Django 2.0.13 on 2019-03-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAstats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='conference_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
