# Generated by Django 2.1.5 on 2019-04-09 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NBAstats', '0003_auto_20190326_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='conference',
            fields=[
                ('conference_id', models.IntegerField(primary_key=True, serialize=False)),
                ('conference_name', models.CharField(blank=True, max_length=10, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NBAstats.Team')),
            ],
        ),
    ]
