# Generated by Django 2.0 on 2019-04-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAstats', '0006_all_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image_path',
            field=models.CharField(blank=True, default='a', max_length=30, null=True),
        ),
    ]
